UX: Allow create-sibling-ria to only act on existing store
datalad/datalad pull request #6045
Opened 2021-10-06 14:22 UTC by adswa

This implements a basic solution to #5982.
The issue is a feature request for the ability to only act on
create-sibling-ria calls if the specified store already
exists. This change adds a parameter to create-sibling-ria,
``'--construct-store'`` (False by default), which, if set, creates a new
store if it doesn't exist under the specified url, and otherwise fails to
create a RIA sibling, warning the user that there is no store at the
specified path. This is an API change to the current release, which
will create a new store if it doesn't find one.

The parameter is intentially not named  ``create-store`` because this would
lead to a name conflict with the ``create_store`` method of ``ria_utils``.

2021-10-06 14:53 UTC, bpoldrack requested changes
Unless there are strong objections to my suggestion I would prefer it to be the other way around. Only the first dataset per store would need to actually create it. Hence, in most cases creation isn't needed. I would go with a `--create-store` flag rather than `expect-store`.
For `maint` its default should probably be `true`, but switch to `false` in `master`. (or not have it in `maint` at all)

2021-10-06 14:53 UTC, bpoldrack commented on datalad/distributed/create_sibling_ria.py
> +        if not io.exists(Path(base_path)) and expect_store:
For consistency with how the ORA remote asses the existence of a store, a valid `ria-layout-version` file at that path is needed, too. Mere existence of the path itself doesn't make it a useable store. Also: `base_path` could be a file and would pass this test.

So, I think change condition to "`io.read_file(Path(base_path)  / 'ria-layout-version')` doesn't raise anything".

2021-10-06 15:02 UTC, adswa commented
Thanks for the review, @bpoldrack!

> Only the first dataset per store would need to actually create it. Hence, in most cases creation isn't needed. I would go with a --create-store flag rather than expect-store.

Sure, also makes sense. In your opinion, what should happen in case of ``--create-store`` at a path of an existing store? Shall we error out, shall we ignore the flag and continue placing a sibling in it, or a "mix" between completely ignoring and erroring with some form of logging? 


> For maint its default should probably be true, but switch to false in master. (or not have it in maint at all)

I'd personally prefer to not have it in maint at all

2021-10-07 06:26 UTC, mih commented
I also see this not targeting `maint` at all.

2021-10-08 09:25 UTC, adswa commented
ok, noted. Just let me know how you would like me to change it.

2021-10-12 05:30 UTC, merged