Allow other URLs than local file as dataset parameter
datalad/datalad pull request #6276
Opened 2021-12-02 11:02 UTC by christian-monch

This PR fixes issue #6275.

The PR removes the restriction of dataset parameters to locally resolvable file-URLs. This is used, for example, in the new metalad version where you can dump metadata from remote repositories.

The main difference introduced is that the decorator `eval_results` only looks for hooks in the default configuration, if the dataset parameter does not specify a locally resolvable file-URL.

2021-12-02 11:24 UTC, bpoldrack approved these changes

2021-12-03 07:26 UTC, mih requested changes
This doesn't work as-is. A plain path is also enough to get a dataset instance, but

```py
In [1]: from datalad.support.network import URL

In [2]: URL('/mike').is_local()
Out[2]: False
```

2021-12-07 09:41 UTC, christian-monch commented
> This doesn't work as-is. A plain path is also enough to get a dataset instance, but
> 
> ```python
> In [1]: from datalad.support.network import URL
> 
> In [2]: URL('/mike').is_local()
> Out[2]: False
> ```

True (I misremembered `urlparse`). The validity determination is now delegated to the Dataset-constructor.

2021-12-10 06:36 UTC, mih approved these changes
This should do it now. Thx!

2021-12-10 06:36 UTC, mih commented
Appveyor failure is unrelated

2021-12-10 06:36 UTC, merged