BF: don't write output from within sshrun
datalad/datalad pull request #7072
Opened 2022-10-07 15:59 UTC by bpoldrack

`datalad sshrun` explicitly calls SSH with `log_output=False` which results in the use of `NoCapture` protocol with the runner. Meaning, stdout/stderr of SSH is written out anyway already. When SSH returns, `sshrun` tried to write both to its stdout/stderr. But: It could not possibly have anything to write. That would not be an issue in and of itself, but `sshrun` is not necessarily used directly. In particular it is called by `git` (due to `GIT_SSH_COMMAND=datalad sshrun`). This resulted in a problem when apparently `git` has closed the pipe to its ssh executable (`sshrun`) already and we tried to write to it (although we really didn't even have something to write).

This ultimately led to issue datalad#6599, where the actual `ssh ... git-upload-pack` execution succeeded and returned 0, but `datalad sshrun` itself produced a broken pipe error trying to write to stdout and hence returning non-zero.

It's not entirely clear when exactly this happens. When exactly the pipe is closed may be depend on git version as the failing builds are running 2.35.1 (MacOS on appveyor) whereas otherbuilds have either newer or older versions of git. In any case:
There can't be anything to write out to begin with, so don't even try.

Closes #6599

2022-10-07 16:09 UTC, mih reviewed
I think a plain removal of these lines is not good. It is all but clear that there could not be any output to write from the code in this file. We are doomed to swallow something important at some point.

If this assertion hold (and needs to hold), an assertion should be in place.

But why not simple guard the write call, and turn it into a best-effort attempt? If a pipe is closed, it wont matter, it could not go anywhere anyways. But of it is open, and there is something, it will come out.

And this seems better than an assertion that does not hold, as it will leave the user with a crash.

WDYT?

2022-10-07 16:16 UTC, bpoldrack commented
@mih : Well, I could do that obviously, but I don't see why. `log_output=False` is unconditional and it should be. A possibly captured output of the SSH call is currently piped through already. Why would we want to change that eventually in favor of a delayed output at the end (same content)? It sabotages any stdin/stdout communication with the caller for no obvious benefit.

2022-10-07 16:47 UTC, bpoldrack commented
@mih : How about this https://github.com/datalad/datalad/pull/7072/commits/2231ba2d751ad0f5a65af8915b2314079cff706e ? (Will squash if you agree).
Thing is: If `out` and `err` exist, future debugging efforts can easily be set on the wrong track, assuming that there should be something in there, since the return value is stored (and even tried to use for writing).

2022-10-08 08:08 UTC, mih commented
Added documentation is essential. Other than that I think the new implementation is as problematic re wrong assumptions about behavior as the one before. Your rational is based on assertions that are not in the code.

Anyways, no need to convince me.

2022-10-08 08:44 UTC, bpoldrack commented
> Your rational is based on assertions that are not in the code.

I honestly don't understand what that assertion is. The now documented behavior of `log_output=False` is the implemented behavior of it and it's the entire point of the switch existing to begin with. I have no idea what "is not in the code". The switch says: "do not grab the output".

To me it's kinda the opposite. If I in 6 months time see `sshrun` implementing something like this:

```
out, err = ssh(...)

try:
   os.write(1, out)
except
   pass
```

I wonder how long it will take me to realize again, that with current implementation there can't be anything in that.

May be I'm not seeing something. I really don't know what it is.


WDYT, @datalad/developers ?

2022-10-11 13:25 UTC, yarikoptic requested changes
my thinking about it -- I think we better `assert` the assumptions of the code especially if there was prior code thinking otherwise

2022-10-11 13:25 UTC, yarikoptic commented on changelog.d/20221007_180414_benjaminpoldrack_fix_6599.md
> +-->
remove all other stubs (even if scriv to remove them, why bother carrying in the diffs etc)?

2022-10-12 13:46 UTC, yarikoptic commented
Thank you @bpoldrack - let's proceed!

2022-10-12 13:46 UTC, merged

2022-10-14 18:45 UTC, yarikoptic-gitmate commented
PR released in [`0.17.7`](https://github.com/datalad/datalad/releases/tag/0.17.7)