PERF: Buffer size optimization from datalad-next
datalad/datalad pull request #7250
Opened 2023-01-12 12:00 UTC by bpoldrack

This is a trivial patch from datalad-next, that significantly improves performance of save,status, etc. b/c of a much too small buffer when the runner is reading output.

2023-01-12 14:51 UTC, yarikoptic commented
CI is red across the board, didn't look in detail but smth is "off".

2023-01-13 08:39 UTC, bpoldrack commented
Oops. Introduced a circular import `consts` <-> `utils`.

2023-01-13 12:57 UTC, yarikoptic requested changes
Changelog needs tune

2023-01-13 12:57 UTC, yarikoptic commented on changelog.d/pr-7250.md
> +- Describe change, possibly reference closed/related issue/PR.
Seems leftover from template

2023-01-15 19:59 UTC, bpoldrack commented on changelog.d/pr-7250.md
> +- Describe change, possibly reference closed/related issue/PR.
Thx.

2023-01-16 11:46 UTC, bpoldrack commented
Ok, fixed changelog, ubuntu's repos are available again and everything passed except for the "old nose code" action with fails during setup. This is #7259 and I'm going to ignore it for this PR. Merging.

2023-01-16 11:46 UTC, merged

2023-01-16 11:47 UTC, yarikoptic-gitmate commented
PR released in [`0.18.1`](https://github.com/datalad/datalad/releases/tag/0.18.1)