ENH: add --cfg-proc to install
datalad/datalad pull request #7477
Opened 2023-08-16 13:54 UTC by bpinsard

Adds the `--cfg-proc` option to install command to allow running commands on dataset post-installation. see #7468 
It runs procedure after recursive install.

It does not call the procedure recursively for now (recursion can be coded in the procedure itself).
Making it recursive would require way more changes to `get` and other parts of the code. 

### PR checklist

- [ ] Write tests.

2023-08-16 14:48 UTC, yarikoptic commented
> It does not call the procedure recursively for now (recursion can be coded in the procedure itself).

I do think that procedure better to operate non-recursively and then indeed it be `get` to actually gain that option first -- the "older style" `install` is pretty much a wrapper around `get` and some folks are just using `datalad clone` and `datalad get` tandem instead of `install`.

2024-03-06 18:45 UTC, yarikoptic commented
Sorry @bpinsard we didn't follow up on this one!
Could you please ideally rebase and force-push so we have a fresh runs of CIs -- and let's aim to see it merged/released.

Other @datalad/developers -- any feedback on this one? looks good and usefull to me.

2024-03-06 18:50 UTC, yarikoptic commented
changelog addition commit got lost, re-added the label. but CI failed to add that commit

```
remote: Permission to courtois-neuromod/datalad.git denied to yarikoptic-gitmate.
fatal: unable to access 'https://github.com/courtois-neuromod/datalad/': The requested URL returned error: 403

```

@bpinsard please permit other maintainers to contribute (I think it is the case why it failed) to this PR (checkmark on the side to the right above IIRC). Or produce it manually using `scriv` tool.

2024-03-06 19:33 UTC, bpinsard commented
Not sure what is wrong in the config, I am pretty sure that I simply forked the repo, what access should I grant and to who and where?

2024-03-06 20:07 UTC, yarikoptic commented
on the right under Paricipants - do you see smth like

![image](https://github.com/datalad/datalad/assets/39889/1c37b29d-e6b7-4516-81af-a46fc1e8fe94)

?  didn't look where generally that is configured in profile

2024-03-06 20:08 UTC, yarikoptic commented
tests fail BTW and need fixing, a sample from appveyor:

```
=========================================================================================================== short test summary info ============================================================================================================
FAILED ../datalad/distribution/tests/test_install.py::test_install_withcfg - TypeError: __call__() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given
FAILED ../datalad/distribution/tests/test_install.py::test_recursive_install_withcfg - TypeError: __call__() takes from 0 to 1 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given
```

2024-03-06 20:15 UTC, yarikoptic commented on datalad/core/local/create.py
> +    # error to prevent creating the dataset.
I think this function should get into datalad/local/run_procedure.py to be along with other procedure support functions:

```shell
❯ git grep 'def _*get.*proc'
datalad/local/run_procedure.py:def _get_proc_config(name, ds=None):
datalad/local/run_procedure.py:def _get_procedure_implementation(name='*', ds=None):
```
and should be named more inline with other function names (although yeah -- already inconsistent above IMHO) and a little more descriptive :

not also I swapped the order of args to be more inline with other 2 functions and renamed arg so body should change too

```suggestion
def _get_proc_configs(names, ds):
    """Get specifications for discovered procedures.
    
     If not a single procedure found, raises `ValueError`
     """
```

2024-03-07 13:58 UTC, bpinsard commented
> on the right under Paricipants - do you see smth like
> 
> ? didn't look where generally that is configured in profile
not it isnt' there.
![image](https://github.com/datalad/datalad/assets/1155388/11bfcccd-56ee-4b99-b980-3bb5f250c235)

2024-03-07 14:25 UTC, yarikoptic commented
interesting -- you are special @bpinsard ! ;-)

ok, nevermind that -- please address my request for harmonization of naming of the helper and address tests fails and I will take care about adding changelog entry later.

2024-03-07 20:55 UTC, bpinsard commented
https://github.com/orgs/community/discussions/5634 because the fork is in an org not an individual...

2024-04-09 19:07 UTC, yarikoptic commented
tests aren't happy
```
FAILED ../datalad/distribution/tests/test_install.py::test_install_withcfg - TypeError: __call__() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given
FAILED ../datalad/distribution/tests/test_install.py::test_recursive_install_withcfg - TypeError: __call__() takes from 0 to 1 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given
```
and may be more -- didn't look in detail.

2024-08-23 19:06 UTC, bpinsard commented
Inconsistent failure of the `datalad/distribution/tests/test_install.py::test_invalid_args` depending on python version, or env or else
https://github.com/datalad/datalad/blob/d4ce9ce377bde2d59fc3a550938b51931dbfbb7b/datalad/distribution/tests/test_install.py#L143 

In my local env (platform linux -- Python 3.10.12, pytest-8.1.1)  it raises IncompleteResultsError rather than TypeError. 
any clue @yarikoptic ?

2025-06-18 20:41 UTC, bpinsard commented
will need https://github.com/datalad/datalad/pull/7735 from more green checks

2026-03-10 17:08 UTC, bpinsard commented
Does it require a change of target branch, or a change of label ?

2026-03-11 01:29 UTC, yarikoptic commented
<img width="1444" height="464" alt="image" src="https://github.com/user-attachments/assets/435b319e-dca7-4030-bd00-e74609cb905a" />

Since it is indeed not a bug fix, let's keep it 'minor' but for that indeed -- target 'master'. I do not think you would even need to rebase. I will request adding changelog entry and will change the base now

2026-03-11 12:04 UTC, yarikoptic requested changes
Indeed might be handy, conflicts accumulated and I left a few comments

2026-03-11 12:04 UTC, yarikoptic commented on datalad/core/distributed/clone.py
> +    from datalad.local.run_procedure import _get_proc_configs
why this import here and not top of the file?  needs a comment if required to be here for some reason

2026-03-11 12:04 UTC, yarikoptic commented on datalad/core/local/create.py
> +        from datalad.local.run_procedure import _get_proc_configs
also this -- move to the top of the file unless required to be here

2026-03-11 12:04 UTC, yarikoptic commented on datalad/distribution/tests/test_install.py
> +    assert (ds.pathobj / 'subds' / 'README.md').exists()
let's fold this into prior test -- our CI already runs LONG time . Can either unlink first install under dest or use two different subfolders

2026-03-13 01:52 UTC, bpinsard commented on datalad/core/distributed/clone.py
> +    from datalad.local.run_procedure import _get_proc_configs
That was a while ago but IIRC there was an import circularity. Will try to figure that out asap.

2026-03-13 13:38 UTC, bpinsard commented on datalad/core/distributed/clone.py
> +    from datalad.local.run_procedure import _get_proc_configs
Just to confirm architectural choice : is the `datalad.core` module not supposed to import non-core modules?  (which would make sense as a core module)
If that's so it's a problem here: I guess we would need to patch `datalad.core.clone.Clone` in `datalad.local.somewhere` , IIUC this is done in datalad-next for some of the commands.

2026-03-14 03:05 UTC, yarikoptic commented on datalad/core/distributed/clone.py
> +    from datalad.local.run_procedure import _get_proc_configs
there might have been an aspiration for .core to indeed stay .core
<details>
<summary>but likely it stayed just an inspiration</summary> 

```shell
❯ git grep 'from datalad\.' -- datalad/core/ | grep -v -e 'datalad.support'  -e /test_
datalad/core/distributed/clone.py:from datalad.cmd import CommandError
datalad/core/distributed/clone.py:from datalad.config import ConfigManager
datalad/core/distributed/clone.py:from datalad.distribution.dataset import (
datalad/core/distributed/clone.py:from datalad.interface.base import (
datalad/core/distributed/clone.py:from datalad.interface.common_opts import (
datalad/core/distributed/clone.py:from datalad.interface.results import get_status_dict
datalad/core/distributed/clone.py:from datalad.utils import (
datalad/core/distributed/clone_ephemeral.py:from datalad.distribution.dataset import Dataset
datalad/core/distributed/clone_ephemeral.py:from datalad.utils import (
datalad/core/distributed/clone_ria.py:from datalad.distribution.dataset import Dataset
datalad/core/distributed/clone_utils.py:from datalad.cmd import (
datalad/core/distributed/clone_utils.py:from datalad.config import ConfigManager
datalad/core/distributed/clone_utils.py:from datalad.distributed.ora_remote import (
datalad/core/distributed/clone_utils.py:from datalad.distribution.dataset import Dataset
datalad/core/distributed/clone_utils.py:from datalad.distribution.utils import _get_flexible_source_candidates
datalad/core/distributed/clone_utils.py:from datalad.dochelpers import single_or_plural
datalad/core/distributed/clone_utils.py:from datalad.log import log_progress
datalad/core/distributed/clone_utils.py:from datalad.runner.exception import CommandError
datalad/core/distributed/clone_utils.py:from datalad.utils import (
datalad/core/distributed/clone_utils.py:    from datalad.interface.common_cfg import definitions
datalad/core/distributed/push.py:from datalad.core.local.diff import diff_dataset
datalad/core/distributed/push.py:from datalad.distribution.dataset import (
datalad/core/distributed/push.py:from datalad.interface.base import (
datalad/core/distributed/push.py:from datalad.interface.common_opts import (
datalad/core/distributed/push.py:from datalad.interface.results import annexjson2result
datalad/core/distributed/push.py:from datalad.interface.utils import render_action_summary
datalad/core/distributed/push.py:from datalad.log import log_progress
datalad/core/distributed/push.py:from datalad.utils import (
datalad/core/distributed/push.py:            from datalad.ui import ui
datalad/core/local/create.py:from datalad.distribution.dataset import (
datalad/core/local/create.py:from datalad.interface.base import (
datalad/core/local/create.py:from datalad.interface.common_opts import location_description
datalad/core/local/create.py:from datalad.utils import (
datalad/core/local/diff.py:from datalad.core.local.status import (
datalad/core/local/diff.py:from datalad.distribution.dataset import (
datalad/core/local/diff.py:from datalad.interface.base import (
datalad/core/local/diff.py:from datalad.utils import (
datalad/core/local/run.py:from datalad.config import anything2bool
datalad/core/local/run.py:from datalad.core.local.save import Save
datalad/core/local/run.py:from datalad.core.local.status import Status
datalad/core/local/run.py:from datalad.distribution.dataset import (
datalad/core/local/run.py:from datalad.distribution.get import Get
datalad/core/local/run.py:from datalad.distribution.install import Install
datalad/core/local/run.py:from datalad.interface.base import (
datalad/core/local/run.py:from datalad.interface.common_opts import (
datalad/core/local/run.py:from datalad.interface.results import get_status_dict
datalad/core/local/run.py:from datalad.interface.utils import generic_result_renderer
datalad/core/local/run.py:from datalad.local.unlock import Unlock
datalad/core/local/run.py:from datalad.ui import ui
datalad/core/local/run.py:from datalad.utils import (
datalad/core/local/run.py:    from datalad.cmd import WitlessRunner
datalad/core/local/save.py:from datalad.distribution.dataset import (
datalad/core/local/save.py:from datalad.interface.base import (
datalad/core/local/save.py:from datalad.interface.common_opts import (
datalad/core/local/save.py:from datalad.interface.utils import (
datalad/core/local/save.py:from datalad.utils import ensure_list
datalad/core/local/status.py:from datalad.distribution.dataset import (
datalad/core/local/status.py:from datalad.dochelpers import single_or_plural
datalad/core/local/status.py:from datalad.interface.base import (
datalad/core/local/status.py:from datalad.interface.common_opts import (
datalad/core/local/status.py:from datalad.interface.utils import generic_result_renderer
datalad/core/local/status.py:from datalad.utils import (
datalad/core/local/status.py:        from datalad.ui import ui
datalad/core/local/status.py:            from datalad.ui import ui
datalad/core/local/status.py:            from datalad.ui import ui
❯ git grep 'from datalad\.local' -- datalad/core/ | grep -v -e 'datalad.support' -e /test_
datalad/core/local/run.py:from datalad.local.unlock import Unlock
```
</details>

if there is a circular import, then indeed should stay in the function but comment added

2026-03-17 17:35 UTC, bpinsard commented on datalad/distribution/tests/test_install.py
> +    assert (ds.pathobj / 'subds' / 'README.md').exists()
Regarding slow tests, 2 observations:

- why do most python3.10 tests actions still install git-annex through miniconda? It is taking 10min just for that, while the pip version is ~1min. 
- profiling some of the tests it seems that `posix.read` account for the biggest share of the time. Do you think there any advantage of using `/dev/shm` as `TMPDIR` for faster IO on github runners for the small file size generated by the test suite?

2026-04-08 00:31 UTC, yarikoptic commented on datalad/distribution/tests/test_install.py
> +    assert (ds.pathobj / 'subds' / 'README.md').exists()
eh, I need to find some quality time to fix up our datalad-installer ... 
- https://github.com/datalad/datalad-installer/pull/219 and others... 
but that is for overall -- kinda independent of the question here. but ok - let's keep separate

2026-04-08 00:37 UTC, yarikoptic commented
you didn't allow pushes from collaborators or just invite me :-/

```shell
❯ git push
ERROR: Permission to courtois-neuromod/datalad.git denied to yarikoptic.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

2026-04-08 17:25 UTC, bpinsard commented
> you didn't allow pushes from collaborators or just invite me :-/
> 
> ```shell
> ❯ git push
> ERROR: Permission to courtois-neuromod/datalad.git denied to yarikoptic.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```

again the org vs user mechanisms, added write permissions to our fork.

2026-04-08 19:16 UTC, yarikoptic commented
coolio -- force pushed now!

2026-04-09 02:56 UTC, yarikoptic commented on datalad/core/distributed/clone.py
> +        cfg_proc=Parameter(
uff -- just now spotted duplicated copies of the `cfg_proc` -- as all other `_opt` reused we should define it centrally and reuse -- no point breeding duplications to maintain...

2026-04-09 13:10 UTC, yarikoptic commented on datalad/core/distributed/clone.py
> +        cfg_proc=Parameter(
pushed

2026-04-09 13:12 UTC, yarikoptic commented
still green, let's proceed! 2.5 years in making ! a record ;)

2026-04-09 13:12 UTC, merged